### ISSUE TITLE
Design of the posts per side

### ISSUE THREAD

**Issue by diehlpk** [OpenDataExpMechanics/platform#12]
![screenshot_2017-07-22_10-36-59](https://user-images.githubusercontent.com/3922435/28492072-cc7ae53e-6ec9-11e7-843a-28f2c17a4f4c.png)

Is it possible to improve the design of the form at the bottom of the page? Such that the button is next to the drop-down menu?

**Comment by adrienthiery** [comment]
It is easily doable yes.

**Comment by diehlpk** [comment]
Ok, cool, I will commit the branch when I finished the functionality.

**Comment by diehlpk** [comment]
Can be fix in feature/pages

**Comment by diehlpk** [comment]
![screenshot_2017-07-23_20-55-28](https://user-images.githubusercontent.com/3922435/28504697-4a7ed9de-6fe9-11e7-9885-12c32f05c4ac.png)

Is it possible to have the number for the pages next to the show button?

**Comment by adrienthiery** [comment]
@diehlpk : I fixed the Layout of the `show` button next to the `all` dropdown in https://github.com/OpenDataExpMechanics/platform/commit/8659d6923534a81489a5ef7e2a890978a93be50c

**Comment by diehlpk** [comment]
@adrienthiery Can you place the numbers next to the show button too?
